apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poc-root
    group: axa-motors
    provider: sumerge
  name: poc-root
spec:
  selector:
    matchLabels:
      app: poc-root
  replicas: 1
  template:
    metadata:
      labels:
        app: poc-root
        group: axa-motors
        provider: sumerge
    spec:
      containers:
        - name: poc-root
          image: @DOCKER_REGISTRY@/axa-motors/poc-root:@BUILD_NUMBER@
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: poc-root
    group: axa-motors
    provider: sumerge
  name: poc-root
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: poc-root
    group: axa-motors
    provider: sumerge
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx-dmz"
  labels:
    app: poc-root
    group: axa-motors
    provider: sumerge
  name: poc-root
spec:
  rules:
    - host: @HOST@
      http:
        paths:
          - backend:
              serviceName: poc-root
              servicePort: 9000
            path: /
