apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poc-utility
    group: axa-motors
    provider: sumerge
  name: poc-utility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-utility
  template:
    metadata:
      labels:
        app: poc-utility
        group: axa-motors
        provider: sumerge
    spec:
      containers:
        - name: poc-utility
          image: @DOCKER_REGISTRY@/@NAMESPACE@/utility:@BUILD_NUMBER@
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: poc-utility
    group: axa-motors
    provider: sumerge
  name: poc-utility
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: poc-utility
    group: axa-motors
    provider: sumerge
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx-dmz"
  labels:
    app: poc-utility
    group: axa-motors
    provider: sumerge
  name: poc-utility
spec:
  rules:
    - host: @HOST@
      http:
        paths:
          - backend:
              serviceName: poc-utility
              servicePort: 80
            path: "/utility(/|$)(.*)"
